model: iFormer_h
batch_size: 128
lr: 8e-3
num_workers: 16
update_freq: 1
model_ema: True
model_ema_eval: True
use_amp: False
save_ckpt_freq: 1
epochs: 300
drop_path: 0.6
layer_scale_init_value: 1e-6
# distillation_type: hard
data_path: imagenet_path
output_dir: output/iFormer_h